---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-web
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: manual
  volumeMode: Filesystem
