---
# 파일 이름 : memcached.yml
# 파드 이름 :  memcached
# 컨테이너 이미지 이름 : memcached123
kind: Pod
apiVersion: v1
metadata:
  name: memcached
spec:
  containers:
  - name: memcached-container
    image: memcached123
