---
kind: Pod
apiVersion: v1
metadata:
  name: pod-annotation
  annotations:
    builder: "KTW(doli001217@gmail.com)"
    builderData: "2025-10-01"
    imageRegistry: "https://hub.docker.com"
spec:
  containers:
    - name: nginx
      image: nginx:1.14
      ports:
      - containerPort: 80